sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t googleio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run googleio/react-test npm test -- --coverage

after_success:
  - docker build -t googleio/multi-client ./client
  - docker build -t googleio/multi-nginx ./nginx
  - docker build -t googleio/multi-server ./server
  - docker build -t googleio/multi-worker ./worker

  #Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push googleio/multi-client
  - docker push googleio/multi-nginx
  - docker push googleio/multi-server
  - docker push googleio/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-evn
  bucket_name: elasticbeanstalk-us-east-2-169832313926
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY