language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t hung6066/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hung6066/react-test npm run test -- --coverage

after_success:
  - docker build -t hung6066/multi-client ./client
  - docker build -t hung6066/multi-nginx ./nginx
  - docker build -t hung6066/multi-server ./server
  - docker build -t hung6066/multi-worker ./worker

#Login in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
- docker push hung6066/multi-client
- docker push hung6066/multi-nginx
- docker push hung6066/multi-server
- docker push hung6066/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-evn
  bucket_name: elasticbeanstalk-us-east-2-169832313926
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY